### ISSUE TITLE
Channel assignment one number off?

### ISSUE THREAD

**Issue by dpentecost** [keijiro/MinisVS#2]
I used MIDI Monitor to check output of both APC-25 and Launch Control XL. Found I had to put one number less for MIDI channel in both note and control in BoltMinis..

For instance, MIDI Monitor shows channel 9 - I have to enter 8 in BoltMinis.

Is this a 0-15 vs 1-16 issue? I see that the default MIDI channel when I opened the Test was 0. (MIDI spec channel nibble 0 hex is channel 1)

Just a guess. Otherwise works great. Thanks!

**Comment by keijiro** [comment]
Your guess is right. When I initially implemented Minis, I solved the problem on the Editor side. I should do the same approach in BoltMinis.

**Comment by dpentecost** [comment]
Cool. Thanks again for this and all the great work.

**Comment by keijiro** [comment]
Fixed in v1.0.1
