### ISSUE TITLE
With Bolt 1.4.15, MinisVS can't use

### ISSUE THREAD

**Issue by mattun** [keijiro/MinisVS#5]
I tried to install MinisVS after installing Bolt, but appear some error messages in the console window.

I wanna use MinisVS.

Please tell me how to fix it.

Thanks

**Comment by keijiro** [comment]
MinisVS is only compatible with Unity's built-in visual scripting system. Unfortunately, there is no compatibility between it and Bolt.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
