### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by gabriverga** [keijiro/MinisVS#6]
Hi! I'm following this tutorial step by step but I am experiencing a problem. (https://www.youtube.com/watch?v=-p1NHYB0GMk&t=3780s)
After installing bolt when I go in the section tools> bolt> unit options wizard and add "minis.visualscriptiong.runtime.asmdef" then in the edit graph I don't see the "Midi Note" or "MIDI Control" node
how can I solve? 

Thanks in advance

Unity 2020.3.27f1

**Comment by gabriverga** [comment]
Is there a project that can be downloaded with everything already installed?

**Comment by keijiro** [comment]
You can use the project in this repository.

**Comment by keijiro** [comment]
The current version of MinisVS doesn't support Bolt -- now it's based on the built-in Unity Visual Scripting system ("formerly known as Bolt"). I'd recommend using Unity 2021.3 instead of 2020.3.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
